### ISSUE TITLE
discord.py attributeerror: 'nonetype' object has no attribute

### ISSUE THREAD

**Issue by kangyoolee** [RobertAndion/Discord_Music_Bot#6]
In music.py
```
import re
import random
import discord
import lavalink
from discord.ext import commands
import asyncio
import fileRead
url_rx = re.compile(r'https?://(?:www\.)?.+')
"""
Robert A. USF Computer Science
A cog to hold all of the functions used to play music for the bot.
"""

class music(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

        if not hasattr(bot, 'lavalink'):  # This ensures the client isn't overwritten during cog reloads.
            bot.lavalink = lavalink.Client(bot.user.id) # <- this is problem
            bot.lavalink.add_node('127.0.0.1', 2333, 'changeme123', 'na', 'local_music_node')
            bot.add_listener(bot.lavalink.voice_update_handler, 'on_socket_response')
```
            
           
----------------------------------------------------------------------------

Traceback (most recent call last):
  File "/Users/kangyoolee/OneDrive/코딩/ssukssugi-test/bot.py", line 14, in <module>
    bot.load_extension(f"Cogs.{filename[:-3]}") #4
  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 678, in load_extension
    self._load_from_module_spec(spec, name)
  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 623, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'Cogs.music' raised an error: AttributeError: 'Bot' object has no attribute 'lavalink'

**Comment by RobertAndion** [comment]
Hello, could you please provide more details about the issue? Thank you

**Comment by kangyoolee** [comment]
How do you solve the this problem?

**Comment by kang309** [comment]
import re
import random
import discord
import lavalink
from discord.ext import commands
import asyncio
import fileRead
url_rx = re.compile(r'https?://(?:www\.)?.+')
"""
Robert A. USF Computer Science
A cog to hold all of the functions used to play music for the bot.
"""

class music(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

        if not hasattr(bot, 'lavalink'):  # This ensures the client isn't overwritten during cog reloads.
            **bot.lavalink = lavalink.Client(bot.user.id) # this part**
            bot.lavalink.add_node('127.0.0.1', 2333, 'changeme123', 'na', 'local_music_node')  # PASSWORD HERE MUST MATCH YML
            bot.add_listener(bot.lavalink.voice_update_handler, 'on_socket_response')
            
           
----------------------------------------------------------------------------


Traceback (most recent call last):
  File "/Users/kangyoolee/OneDrive/코딩/ssukssugi-test/bot.py", line 14, in <module>
    bot.load_extension(f"Cogs.{filename[:-3]}") #4
  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 678, in load_extension
    self._load_from_module_spec(spec, name)
  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 623, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'Cogs.music' raised an error: AttributeError: 'Bot' object has no attribute 'lavalink'

**Comment by RobertAndion** [comment]
Have you done pip3 install lavalink?

**Comment by kangyoolee** [comment]
Yes.

**Comment by RobertAndion** [comment]
I would advise doing a fresh pull, just save your env file and then try again, also I see it is in a OneDrive folder and python may not like that, I would try a regular directory on your PC, if that doesn't work we can work on it more later today, I personally have not run across this error yet. If you continue to have trouble, if you have docker you can run the docker file and it will auto-install everything, the documentation for that exists but isn't super clear yet, feel free to ask questions on it if you want to try that route.

**Comment by RobertAndion** [comment]
Is the issue resolved?

**Comment by kangyoolee** [comment]
Yes

2021년 8월 6일 (금) 오후 11:39, Robert Andion ***@***.***>님이 작성:

**Comment by RobertAndion** [comment]
Perfect glad to hear it
